parameters:
  jobName: ''
  vmImage: ''
  publishBuildArtifactsArtifactName: ''

jobs:
- job: ${{ parameters.jobName }}
  displayName: Publish Build Artifacts
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
    DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    configuration: 'Release'
    # buildPlatform: 'Any CPU'
    verbosity: 'normal'
  steps:
  - task: PowerShell@2
    displayName: 'Build, Pack & Test'
    inputs:
      filePath: '$(Build.SourcesDirectory)\build.ps1'
      # test depeneds on [ build, pack ]
      arguments: 'test --configuration $(configuration) --verbosity $(verbosity)'
      
  - task: CopyFiles@2
    displayName: 'Copy Build Artifacts'
    inputs:
      Contents: $(Build.SourcesDirectory)/src/**/bin/$(configuration)/*.?(s)nupkg
      TargetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      TargetPath: $(Build.ArtifactStagingDirectory)
      ArtifactName: ${{ parameters.publishBuildArtifactsArtifactName }}
      publishLocation: Container