# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  # solution: '**/*.sln'
  solution: 'src/Core/Core.sln'

steps:
- task: DotNetCoreCli@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(solution)'
# The last task is a nuget command, nuget push
# This will push any .nupkg files to the 'TestFeed' artifact feed
# allowPackageConflicts allows us to build the same version and not throw an error when trying to push
# instead it just ingores the latest package unless the version changes
- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    # feedsToUse: 'config'
    # feedsToUse: 'select'
    # vstsFeed: 'TestFeed2'
    packagesToPush: '**/*.nupkg;!**/*.snupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Teronis.NetStandard/TestFeed2'
    versioningScheme: 'off'
    # nugetConfigPath: '$(Build.SourcesDirectory)/nuget.config'
