# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop
- releases/*
- features/*
- pull-requests/*
- hotfixes/*
- support/*

variables:
  - template: shared-variables.yml

jobs:
- template: publish-build-artifacts-job.yml
  parameters:
    vmImage: ${{ variables.vmImage }}
  